apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
spec:
  selector:
    matchLabels:
      app: java-app
  replicas: 1
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: tabrezid54/java-app:__Build.BuildId__
          ports:
          - containerPort: 8080
          env:
          - name: SPRING_CONFIG_LOCATION
            value: /usr/local/tomcat/webapps/application.properties
          ports:
          - containerPort: 8088
          volumeMounts:
          - name: db-info
            mountPath: /usr/local/tomcat/webapps/application.properties
            subPath: application.properties
            readOnly: true
      volumes:
      - name: db-info
        configMap:
          name: application-properties

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: application-properties
data:
  application.properties: |
    spring.mvc.view.prefix=/pages/
    spring.mvc.view.suffix=.jsp
    spring.datasource.url = __DB_URL__
    spring.datasource.username = __DB_USER__
    spring.datasource.password = __DB_PASSWORD__

---

apiVersion: v1 
kind: Service 
metadata: 
  name: java-app-svc
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
    - protocol: "TCP"
      port: 8080
      nodePort: 30008
