apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: webcolor
  ports:
    - port: 80
      name: app1
      targetPort: 8080
      nodePort: 30008
    - port: 90
      name: app2
      targetPort: 80
      nodePort: 30010
